package com.wci.backend.interpreter;

import com.wci.intermediate.ICode;
import com.wci.intermediate.SymTab;
import com.wci.backend.*;
import com.wci.message.*;

import static com.wci.message.MessageType.INTERPRETER_SUMMARY;

public class Executor extends Backend{

    /**
     * Process the intermeidate code and the symbol table generated by the 
     * parser to execute the source program.
     * @param iCode the intermediate code.
     * @param symTab the symbol table.
     * @throws Exception if an error occurred.
     */
    public void process(ICode iCode, SymTab symTab) throws Exception{
	long startTime = System.currentTimeMillis();
	float elapsedTime = (System.currentTimeMillis() - startTime)/1000f;
	int executionCount = 0;
	int runtimeErrors = 0;

	// Send the interpreter summary message.
	sendMessage(new Message(INTERPRETER_SUMMARY, new Number[] {executionCount,
								   runtimeErrors,
								   elapsedTime}));
    }
}
