package wci.backend;

import wci.backend.ICode;
import wci.backend.SymTab;


public class Executor extends Backend{

    /**
     * Process the intermeidate code and the symbol table generated by the 
     * parser to execute the source program.
     * @param iCode the intermediate code.
     * @param symTab the symbol table.
     * @throws Exception if an error occurred.
     */
    public void process throws Exception(ICode iCode, SymTab symTab){
	long startTime = System.currentTimeMillis();
	float elapsedTime = (System.currentTimeMillis() - startTime)/1000f;
	int executionCount = 0;
	int runtimeErrors = 0;

	// Send the interpreter summary message.
	sendMessage(new Message(INTERPRETER_SUMMARY, new Number[] {executionCount,
								   / runtimeErrors,
								   / elapsedTime});
    }
}
